name: Build for Windows
description: 'Build V8 for Windows'

inputs:
  archive-name:
    description: 'Base name of the archive to create'
    default: v8_Windows
    required: false
    type: string
  target-cpu:
    description: 'Optional target CPU override (e.g. arm64)'
    default: ''
    required: false
    type: string
  run-tests:
    description: 'Run sample smoke test'
    default: 'false'
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - name: Restore SCCache
      uses: actions/cache@v4
      with:
        path: .sccache
        key: ${{ runner.os }}-${{ runner.arch }}:libv8:sccache:${{ github.run_number }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}:libv8:sccache:

    - name: Setup Scoop
      if: runner.arch != 'ARM64'
      uses: MinoruSekine/setup-scoop@v4

    - name: Setup Build Tools
      shell: pwsh
      run: |
        $ErrorActionPreference = 'Stop'

        if ("${{ runner.arch }}" -ne "ARM64") {
          scoop install sccache llvm
        } else {
          Write-Host 'Skipping Scoop package install on ARM64 runner'
        }

        if (Get-Command sccache -ErrorAction SilentlyContinue) {
          $sccacheDir = "$Env:GITHUB_WORKSPACE`\.sccache"
          New-Item -Path "$sccacheDir" -ItemType Directory -Force | Out-Null
          Write-Output "SCCACHE_DIR=$sccacheDir" | Out-File -FilePath "$Env:GITHUB_ENV" -Encoding utf8
        } else {
          Write-Host 'sccache not found; building without compiler cache'
        }

        if (Get-Command llvm-ar -ErrorAction SilentlyContinue) {
          Write-Host 'llvm-ar found'
        } else {
          Write-Host 'llvm-ar not found; archive deconflict will use lib.exe fallback'
        }

    - name: Download V8 Source
      shell: cmd
      run: .\v8_download.bat

    - name: Compile V8
      shell: cmd
      env:
        TARGET_CPU: ${{ inputs.target-cpu }}
      run: .\v8_compile.bat

    - name: Show SCCache Status
      shell: pwsh
      run: |
        if (Get-Command sccache -ErrorAction SilentlyContinue) {
          sccache --show-stats
        } else {
          Write-Host 'sccache not installed; skipping stats'
        }

    - name: Setup Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1

    - name: Test V8
      if: ${{ inputs.run-tests == 'true' }}
      shell: cmd
      run: .\v8_test.bat

    - name: Archive V8
      shell: pwsh
      run: .\archive.bat ${{ inputs.archive-name }}
