name: Build for Windows
description: 'Build V8 for Windows'

inputs:
  archive-name:
    description: 'Base name of the archive to create'
    default: v8_Windows
    required: false
    type: string
  target-cpu:
    description: 'Optional target CPU override (e.g. arm64)'
    default: ''
    required: false
    type: string
  run-tests:
    description: 'Run sample smoke test'
    default: 'false'
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - name: Restore SCCache
      uses: actions/cache@v4
      with:
        path: .sccache
        key: ${{ runner.os }}-${{ runner.arch }}:libv8:sccache:${{ github.run_number }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}:libv8:sccache:

    - name: Setup Scoop
      if: runner.arch != 'ARM64'
      uses: MinoruSekine/setup-scoop@v4

    - name: Setup Build Tools
      shell: pwsh
      run: |
        $ErrorActionPreference = 'Stop'

        if ("${{ runner.arch }}" -ne "ARM64") {
          scoop install sccache llvm
        } else {
          Write-Host 'Skipping Scoop package install on ARM64 runner'
        }

        if (Get-Command sccache -ErrorAction SilentlyContinue) {
          $sccacheDir = "$Env:GITHUB_WORKSPACE`\.sccache"
          New-Item -Path "$sccacheDir" -ItemType Directory -Force | Out-Null
          Write-Output "SCCACHE_DIR=$sccacheDir" | Out-File -FilePath "$Env:GITHUB_ENV" -Encoding utf8
        } else {
          Write-Host 'sccache not found; building without compiler cache'
        }

        if (Get-Command llvm-ar -ErrorAction SilentlyContinue) {
          Write-Host 'llvm-ar found'
        } else {
          Write-Host 'llvm-ar not found; archive deconflict will use lib.exe fallback'
        }

    - name: Select System Clang Toolchain
      shell: pwsh
      run: |
        $ErrorActionPreference = 'Stop'

        $targetCpu = "${{ inputs.target-cpu }}"
        if ([string]::IsNullOrWhiteSpace($targetCpu)) {
          $targetCpu = 'x64'
        }
        $targetCpu = $targetCpu.ToLowerInvariant()

        $requiredBuiltins = if ($targetCpu -eq 'arm64') {
          'clang_rt.builtins-aarch64.lib'
        } else {
          'clang_rt.builtins-x86_64.lib'
        }

        $candidates = @()
        $pathClang = Get-Command clang-cl.exe -ErrorAction SilentlyContinue
        if ($pathClang) {
          $candidates += $pathClang.Source
        }

        foreach ($edition in @('Enterprise', 'Professional', 'Community', 'BuildTools')) {
          $candidate = "C:\Program Files\Microsoft Visual Studio\2022\$edition\VC\Tools\Llvm\x64\bin\clang-cl.exe"
          if (Test-Path $candidate) {
            $candidates += $candidate
          }
        }

        $programFilesLlvm = 'C:\Program Files\LLVM\bin\clang-cl.exe'
        if (Test-Path $programFilesLlvm) {
          $candidates += $programFilesLlvm
        }

        $candidates = $candidates | Select-Object -Unique
        if ($candidates.Count -eq 0) {
          throw 'No clang-cl candidates found on runner.'
        }

        $selected = $null
        foreach ($clangCl in $candidates) {
          $resourceDir = (& $clangCl -print-resource-dir 2>$null | Out-String).Trim()
          if (-not $resourceDir) {
            continue
          }

          $builtins = Join-Path $resourceDir ("lib\windows\" + $requiredBuiltins)
          if (Test-Path $builtins) {
            $selected = [PSCustomObject]@{
              ClangCl = $clangCl
              ResourceDir = $resourceDir
              Builtins = $builtins
            }
            break
          }
        }

        if (-not $selected) {
          throw "No clang-cl candidate provides $requiredBuiltins for target_cpu=$targetCpu."
        }

        $clangVersion = Split-Path $selected.ResourceDir -Leaf
        $clangBasePath = (Resolve-Path (Join-Path $selected.ResourceDir '..\..\..')).Path
        $clangBasePath = $clangBasePath -replace '\\', '/'

        "V8_CLANG_BASE_PATH=$clangBasePath" | Out-File -FilePath "$Env:GITHUB_ENV" -Encoding utf8 -Append
        "V8_CLANG_VERSION=$clangVersion" | Out-File -FilePath "$Env:GITHUB_ENV" -Encoding utf8 -Append

        Write-Host "Using clang-cl: $($selected.ClangCl)"
        Write-Host "Using clang resource dir: $($selected.ResourceDir)"
        Write-Host "Validated builtins library: $($selected.Builtins)"

    - name: Download V8 Source
      shell: cmd
      run: .\v8_download.bat

    - name: Compile V8
      shell: cmd
      env:
        TARGET_CPU: ${{ inputs.target-cpu }}
      run: .\v8_compile.bat

    - name: Show SCCache Status
      shell: pwsh
      run: |
        if (Get-Command sccache -ErrorAction SilentlyContinue) {
          sccache --show-stats
        } else {
          Write-Host 'sccache not installed; skipping stats'
        }

    - name: Setup Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1

    - name: Test V8
      if: ${{ inputs.run-tests == 'true' }}
      shell: cmd
      run: .\v8_test.bat

    - name: Archive V8
      shell: pwsh
      run: .\archive.bat ${{ inputs.archive-name }}
