name: Build for Windows
description: 'Build V8 for Windows'

inputs:
  archive-name:
    description: 'Base name of the archive to create'
    default: v8_Windows
    required: false
    type: string
  target-cpu:
    description: 'Optional target CPU override (e.g. arm64)'
    default: ''
    required: false
    type: string
  run-tests:
    description: 'Run sample smoke test'
    default: 'false'
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - name: Restore SCCache
      uses: actions/cache@v4
      with:
        path: .sccache
        key: ${{ runner.os }}-${{ runner.arch }}:libv8:sccache:${{ github.run_number }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}:libv8:sccache:

    - name: Setup Scoop
      if: runner.arch != 'ARM64'
      uses: MinoruSekine/setup-scoop@v4

    - name: Setup Build Tools
      shell: pwsh
      run: |
        $ErrorActionPreference = 'Stop'
        $targetCpu = "${{ inputs.target-cpu }}"
        if ([string]::IsNullOrWhiteSpace($targetCpu)) {
          $targetCpu = 'x64'
        }
        $targetCpu = $targetCpu.ToLowerInvariant()

        if ($targetCpu -eq 'arm64') {
          scoop install sccache llvm llvm-arm64
        } else {
          scoop install sccache llvm
        }

        if (Get-Command sccache -ErrorAction SilentlyContinue) {
          $sccacheDir = "$Env:GITHUB_WORKSPACE`\.sccache"
          New-Item -Path "$sccacheDir" -ItemType Directory -Force | Out-Null
          Write-Output "SCCACHE_DIR=$sccacheDir" | Out-File -FilePath "$Env:GITHUB_ENV" -Encoding utf8
        } else {
          Write-Host 'sccache not found; building without compiler cache'
        }

        if (Get-Command llvm-ar -ErrorAction SilentlyContinue) {
          Write-Host 'llvm-ar found'
        } else {
          Write-Host 'llvm-ar not found; archive deconflict will use lib.exe fallback'
        }

    - name: Select System Clang Toolchain
      shell: pwsh
      run: |
        $ErrorActionPreference = 'Stop'

        $targetCpu = "${{ inputs.target-cpu }}"
        if ([string]::IsNullOrWhiteSpace($targetCpu)) {
          $targetCpu = 'x64'
        }
        $targetCpu = $targetCpu.ToLowerInvariant()

        $requiredBuiltins = if ($targetCpu -eq 'arm64') {
          @(
            'clang_rt.builtins-aarch64.lib',
            'clang_rt.builtins-arm64.lib'
          )
        } else {
          @('clang_rt.builtins-x86_64.lib')
        }
        $canonicalBuiltins = if ($targetCpu -eq 'arm64') {
          'clang_rt.builtins-aarch64.lib'
        } else {
          'clang_rt.builtins-x86_64.lib'
        }

        $candidates = @()
        $scoopLlvmClang = Join-Path $Env:USERPROFILE 'scoop\apps\llvm\current\bin\clang-cl.exe'
        if (Test-Path $scoopLlvmClang) {
          $candidates += $scoopLlvmClang
        }
        $scoopShimClang = Join-Path $Env:USERPROFILE 'scoop\shims\clang-cl.exe'
        if (Test-Path $scoopShimClang) {
          $candidates += $scoopShimClang
        }

        $pathClang = Get-Command clang-cl.exe -ErrorAction SilentlyContinue
        if ($pathClang) {
          $candidates += $pathClang.Source
        }

        foreach ($edition in @('Enterprise', 'Professional', 'Community', 'BuildTools')) {
          $candidate = "C:\Program Files\Microsoft Visual Studio\2022\$edition\VC\Tools\Llvm\x64\bin\clang-cl.exe"
          if (Test-Path $candidate) {
            $candidates += $candidate
          }
        }

        $programFilesLlvm = 'C:\Program Files\LLVM\bin\clang-cl.exe'
        if (Test-Path $programFilesLlvm) {
          $candidates += $programFilesLlvm
        }

        $candidates = $candidates | Select-Object -Unique
        if ($candidates.Count -eq 0) {
          throw 'No clang-cl candidates found on runner.'
        }

        $selected = $null
        foreach ($clangCl in $candidates) {
          $resourceDir = (& $clangCl -print-resource-dir 2>$null | Out-String).Trim()
          if (-not $resourceDir) {
            continue
          }

          foreach ($builtinsName in $requiredBuiltins) {
            $builtins = Join-Path $resourceDir ("lib\windows\" + $builtinsName)
            if (-not (Test-Path $builtins)) {
              continue
            }

            $canonicalBuiltinsPath = Join-Path $resourceDir ("lib\windows\" + $canonicalBuiltins)
            if ($builtinsName -ne $canonicalBuiltins -and -not (Test-Path $canonicalBuiltinsPath)) {
              Copy-Item -Path $builtins -Destination $canonicalBuiltinsPath -Force
            }

            $selected = [PSCustomObject]@{
              ClangCl = $clangCl
              ResourceDir = $resourceDir
              Builtins = $canonicalBuiltinsPath
            }
            break
          }
          if ($selected) {
            break
          }
        }

        if (-not $selected -and $targetCpu -eq 'arm64') {
          $armRuntimeRoot = Join-Path $Env:USERPROFILE 'scoop\apps\llvm-arm64\current\lib\clang'
          if (Test-Path $armRuntimeRoot) {
            $armRuntimeDirs = Get-ChildItem -Path $armRuntimeRoot -Directory -ErrorAction SilentlyContinue
            foreach ($clangCl in $candidates) {
              $resourceDir = (& $clangCl -print-resource-dir 2>$null | Out-String).Trim()
              if (-not $resourceDir) {
                continue
              }

              $destRuntimeDir = Join-Path $resourceDir 'lib\windows'
              if (-not (Test-Path $destRuntimeDir)) {
                continue
              }

              foreach ($armRuntimeDir in $armRuntimeDirs) {
                foreach ($armBuiltinsName in @('clang_rt.builtins-aarch64.lib', 'clang_rt.builtins-arm64.lib')) {
                  $srcBuiltins = Join-Path $armRuntimeDir.FullName ("lib\windows\" + $armBuiltinsName)
                  if (-not (Test-Path $srcBuiltins)) {
                    continue
                  }

                  $destBuiltins = Join-Path $destRuntimeDir 'clang_rt.builtins-aarch64.lib'
                  Copy-Item -Path $srcBuiltins -Destination $destBuiltins -Force
                  $selected = [PSCustomObject]@{
                    ClangCl = $clangCl
                    ResourceDir = $resourceDir
                    Builtins = $destBuiltins
                  }
                  break
                }
                if ($selected) {
                  break
                }
              }
              if ($selected) {
                break
              }
            }
          }
        }

        if (-not $selected) {
          $requiredBuiltinsDisplay = $requiredBuiltins -join ', '
          throw "No clang-cl candidate provides any of [$requiredBuiltinsDisplay] for target_cpu=$targetCpu."
        }

        $clangVersion = Split-Path $selected.ResourceDir -Leaf
        $clangBasePath = (Resolve-Path (Join-Path $selected.ResourceDir '..\..\..')).Path
        $clangBasePath = $clangBasePath -replace '\\', '/'

        "V8_CLANG_BASE_PATH=$clangBasePath" | Out-File -FilePath "$Env:GITHUB_ENV" -Encoding utf8 -Append
        "V8_CLANG_VERSION=$clangVersion" | Out-File -FilePath "$Env:GITHUB_ENV" -Encoding utf8 -Append

        Write-Host "Using clang-cl: $($selected.ClangCl)"
        Write-Host "Using clang resource dir: $($selected.ResourceDir)"
        Write-Host "Validated builtins library: $($selected.Builtins)"

    - name: Download V8 Source
      shell: cmd
      run: .\v8_download.bat

    - name: Compile V8
      shell: cmd
      env:
        TARGET_CPU: ${{ inputs.target-cpu }}
      run: .\v8_compile.bat

    - name: Show SCCache Status
      shell: pwsh
      run: |
        if (Get-Command sccache -ErrorAction SilentlyContinue) {
          sccache --show-stats
        } else {
          Write-Host 'sccache not installed; skipping stats'
        }

    - name: Setup Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1

    - name: Test V8
      if: ${{ inputs.run-tests == 'true' }}
      shell: cmd
      run: .\v8_test.bat

    - name: Archive V8
      shell: pwsh
      run: .\archive.bat ${{ inputs.archive-name }}
